### ISSUE TITLE
Addition of new fields

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-tms-extract#82]
M+ will be adding some new fields to the data export soon. There will be a test XML in `/test` on the admin server. Once they are present, we will need to make sure they find their way to the API ( and eventually the Spelunker ) but first the API!

@dianewang can you please list the additional fields being added in this first round?

**Comment by dianewang** [comment]
Absolutely. Here's a list of the records that are included as well as specific IDs for Sigg Online, so that you can test the data in the API! I've confirmed with Jim that the only new fields this time around were Sigg related.

**For Record Selection**
_Exhibitions_
ExhObjeXrefs.ExhibitionID = 95
Exhibitions.ExhTitle = 'Sigg Online'
 
_Featured Works:_
ExhObjeXrefs.Section = 'Featured Work'
 
_Related Works:_
ExhObjeXrefs.Section = 'Related Work'
 
**Object Descriptions**
_TextEntries_
TexttypeID = 33
Purpose = 'Sigg Online Exhibition'
LanguageID = 9 (UK English)
LanguageID = 18 (Traditional Chinese)
 
**Constituent Bios**
_TextEntries_
TextTypeID = 78 ('Exhibition Bio')
Purpose = 'Sigg Online Exhibition'
LanguageID = 9 (UK English)
LanguageID = 18 (Traditional Chinese)
 
**Alt Text**
_TextEntries_
TextTypeID = 77 ('Alt Text')
LanguageID = 9 (UK English)
LanguageID = 18 (Traditional Chinese)
